### ISSUE TITLE
update 03_Maintenance/32_Tyres required

### ISSUE THREAD

**Issue by mi-hol** [Engenia/Engenia#14]
The mentioned tires are no longer available.
How about removing at least the copyrighted reviews to prevent any issues?

Eventually just mentioning what tires have been used successfully?

**Comment by Engenia** [comment]
If and when copyright becomes an issue, I'll simply remove the pdf's. I doubt very much that anyone would take issue with an obsolete review.
I think that anyone reading the page would realise the subject has been superceded. The date at the top should be a giveaway.

**Comment by mi-hol** [comment]
> If and when copyright becomes an issue, I'll simply remove the pdf's.

you might be lucky to get away with this approach with an .au domain 

In Germany specialized law firms made it their business to find and charge 1000€ per copyright violation found

**Comment by Engenia** [comment]
The .au site's been running for many years without being bothered, but this might become a problem for the github site. Then again, the only people using that site will be those from the forum. A google search is unlikely to find it.
If a German firm found it and charged me for the violation, I doubt they'd extradite me to Germany to face court when I failed to pay it.
