### ISSUE TITLE
folder "04_Body/01_General/Decals" not referenced

### ISSUE THREAD

**Issue by mi-hol** [Engenia/Engenia#15]
fix or delete?

**Comment by Engenia** [comment]
You're welcome to add the necessary menu.
Someone, maybe even me, will find that file useful.
The Debeer paint mix for Tornado Red should be referenced as well. That, is "gold".

**Comment by mi-hol** [comment]
I was wrong, its actually referenced in https://engenia.github.io/Engenia/04_Body/01_General/Paint.html
