### ISSUE TITLE
folder "09_Electrical/10_SafetySystem" not referenced!

### ISSUE THREAD

**Issue by mi-hol** [Engenia/Engenia#16]
likely a bug!

**Comment by Engenia** [comment]
More source code that has been included with a view to make it available.
In this case, if you try to work out how the safety system works from the wiring diagram, it'll take ages. I created this png to save me the trouble.
You're welcome to add the necessary menu.

**Comment by mi-hol** [comment]
added in Diagnostics menu because this seems the more logical place when its needed :)
PR will come later

**Comment by mi-hol** [comment]
Are the source files for:
[Tornado RS Safety System.pdf](https://github.com/Engenia/Engenia/blob/main/09_Electrical/10_SafetySystem/Tornado%20RS%20Safety%20System.pdf)
[TornadoSafetySystem.png](https://github.com/Engenia/Engenia/blob/main/09_Electrical/10_SafetySystem/TornadoSafetySystem.png)
still on your PC?
The text is a bit small, so I would prefer to make the font bigger for better readability, before publishing them.

**Comment by Engenia** [comment]
I do have them, but the effort required to change them is disproportionate to the advantages of an increased font size. It is so low on the todo list that it's unlikely I'll ever get to it.
If you want to import them into GIMP, erase the current text and insert text of a size you deem to be suitable, go right ahead. I'll check them before they are released.
Thinking about it, I think the two safety systems should be available in the same format to make them more easily compared. Both saved as jpegs would be my preference.

**Comment by mi-hol** [comment]
1. How about just uploading the current source files here? So I can figure it out
2. jpeg has much worse clarity if text is involved, png is much a much better format in this case

**Comment by Engenia** [comment]
I just had a look in the source on github. Those files are there.

**Comment by mi-hol** [comment]
Maybe I am getting blind but can't seem to see them in folder 09_Electrical/10_SafetySystem :(

**Comment by Engenia** [comment]
![engenia electrical safetysystem](https://github.com/user-attachments/assets/0e2a0d33-d828-442c-a7b3-7faf30f08d80)

**Comment by mi-hol** [comment]
but neither the pdf nor the png is the real source. The real source seems a CAD drawing

**Comment by mi-hol** [comment]
![image](https://github.com/user-attachments/assets/dcaa8a79-a6bd-43b2-92cf-41a25d62c3e2)

**Comment by Engenia** [comment]
The schematics were developed in Altium
Here's the one for the RS home/errol/Dropbox/Project/Tornado/Safety/RSSftySys.Sch

**Comment by Engenia** [comment]
[RSSftySys.zip](https://github.com/user-attachments/files/17264356/RSSftySys.zip)
This is the one for the RS

**Comment by Engenia** [comment]
can you open it?

**Comment by mi-hol** [comment]
Unfortunately not, tried with KiCad 8, which supports import from Altrium version 6 or later (at least [manual says that here](https://docs.kicad.org/8.0/de/kicad/kicad.html#importing_a_project_from_another_eda_tool)), but got
![image](https://github.com/user-attachments/assets/9b20addb-8031-46cc-b5c4-ae97aba5f8b8)

Would it be feasible to open and save the file with Altrium version 6 or later on your side, then attach this file here again?

**Comment by Engenia** [comment]
Altium 6 is v v old. I'm using 18. Not sure if it can even save in such an
old format.
regards
Errol

**Comment by Engenia** [comment]
I just quickly cut & shut the two schematics & uploaded as jpegs. The relative text sizes should now be a bit larger.
 I think they're good enough to show the systems. Way better than trying to follow the wiring diagrams

**Comment by mi-hol** [comment]
> I just quickly cut & shut the two schematics & uploaded as jpegs.

True, much better.


> Altium ...  I'm using 18. 

Apologize the initial comment re Altium was revised but you likely didn't see it because GH doesn't resend changes via email.

In short, could you please open RSSftySys.Sch in Altium 18, then save it as a new file. This should give it a different file extension supported by KiCad 8

**Comment by Engenia** [comment]
Now that I've seen the menu in action, the diagnostics menu is a bit busy. The Safety System item should be broken down to a sub level where selection between Tornado & Tornado RS can be made.
I also don't think that these schematics are specifically diagnostics, although they could be used in that endeavour. If I was looking for the Safety System I would first look under Electrical. The wiring error page should be there also.
When we talk about diagnostics, we are referring to the bike, not it's documentation.
