### ISSUE TITLE
Add https://engenia.github.io/Engenia/ to "About" 

### ISSUE THREAD

**Issue by mi-hol** [Engenia/Engenia#5]
@Engenia this change would allow users to directly access the generated website

![image](https://github.com/Engenia/Engenia/assets/22799428/d1661053-aa34-4bad-ac93-2184abb69e92)

**Comment by Engenia** [comment]
You're going to have to be more explicit Michael.
What is it you want me to do precisely?
How will it allow users to directly access the website?

I'm a newby at this. I understood that it was public, and anyone who entered "engenia.github.io/Engenia/" into their browser could access it.

**Comment by mi-hol** [comment]
Sorry, I meant, text in "About" should be changed to:
"https://engenia.github.io/Engenia/  is the alternative URL to use in case http://engenia.com.au is down"

This way newbies could just click on the link instead of needing to know to manually enter https://engenia.github.io/Engenia/
In other works this change  makes it more simple and user friendly to access the alternative website.
Hope it makes sense now.

**Comment by Engenia** [comment]
'tis done
There's already a link to it on the Benelliforum/Tornado "Really Useful Tornado Page"
